require 'bundler'
require "bundler/gem_tasks"
require "open-uri"

Bundler.require

task :default => [:spec]
require 'rspec/core/rake_task'
desc "Run specs"
RSpec::Core::RakeTask.new do |t|
  t.rspec_opts = %w(-fd --color)
end

desc "Rebuild with latest area code mappings from e164.js"
task :rebuild do
  # Update mappings
  js_mappings = URI.open('https://raw.githubusercontent.com/remind101/e164.js/master/e164.js').read
  mappings = js_mappings.scan(/"([\d]+)\": \[\s*(.+?)\s*\],/)
  lookup_file = File.open('lib/e164/lookuptable.rb', 'w')
  lookup_file.write('# This file is automatically generated by `rake rebuild`
module E164
  LookupTable = {
')
  for mapping in mappings
    lookup_file.write("    \"#{mapping[0]}\" => [#{mapping[1]}],\n")
  end
  lookup_file.write('  }
end')
  lookup_file.close()

  # Sync up version
  js_manifest = URI.open('https://raw.githubusercontent.com/remind101/e164.js/master/package.json').read
  version = js_manifest.match(/version":\s*"([\d.]+)"/).captures[0]
  version_file = File.open('lib/e164/version.rb', 'w')
  version_file.write("module E164
  VERSION = \"#{version}\"
end
")
  version_file.close()
end
